#!/usr/bin/env bash
#
#
#  @author     Zac Dreyer [D3V.Digital]
#  @license    LICENSE
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


PROCESS_NUM=$(ps -ef | grep "d3vskyman.py" | grep -v "grep" | wc -l)
if [ $PROCESS_NUM -eq 0 ];
then
	echo "Starting process d3vskyman"
	python /path/to/d3v-skyman/d3vskyman.py 2> /dev/null &
else
     echo "d3vskyman already active"
fi